@startuml
title Facade - clases
class OrderFacade { +placeOrder(sku, account) }
class Inventory { +hasStock(sku): boolean }
class Payment { +charge(account) }
class Shipping { +schedule(sku) }
class Client
Client --> OrderFacade : usa API simple
OrderFacade --> Inventory
OrderFacade --> Payment
OrderFacade --> Shipping
@enduml

@startuml
title Facade - interaccion
participant Client
participant OrderFacade
participant Inventory
participant Payment
participant Shipping
Client -> OrderFacade : placeOrder(sku, account)
OrderFacade -> Inventory : hasStock(sku)
Inventory --> OrderFacade : true
OrderFacade -> Payment : charge(account)
OrderFacade -> Shipping : schedule(sku)
OrderFacade --> Client : orden aceptada
@enduml
